apiVersion: batch/v1
kind: Job
metadata:
  name: rcm-label-nodes
spec:
  template:
    metadata:
      name: rcm-label-nodes
    spec:
      serviceAccountName: rcm-label-nodes-sa
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command: ["kubectl"]
        args: ["label", "node", "--all", "spin=true"]
      restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rcm-label-nodes-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rcm-label-nodes-clusterrole
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rcm-label-nodes-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rcm-label-nodes-clusterrole
subjects:
- kind: ServiceAccount
  name: rcm-label-nodes-sa
  namespace: default