name: Marketplace Smoketest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # This version should match the (forked) version of the spin-operator sub-chart
  SPIN_OPERATOR_VERSION: v0.3.0

jobs:
  helm-install-smoke-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install helm
        uses: Azure/setup-helm@v4
        with:
          version: v3.15.4

      - name: create kind cluster
        uses: helm/kind-action@v1

      - name: helm install spinkube
        run: |
          helm install spinkube \
            --wait \
            --namespace spinkube \
            --create-namespace \
            --debug \
            marketplace/charts/spinkube-azure-marketplace

      - name: run spin app
        run: |
          kubectl apply -f https://raw.githubusercontent.com/spinkube/spin-operator/${{ env.SPIN_OPERATOR_VERSION }}/config/samples/simple.yaml
          kubectl rollout status deployment simple-spinapp --timeout 90s
          kubectl get pods -A
          kubectl port-forward svc/simple-spinapp 8083:80 &
          timeout 15s bash -c 'until curl -f -vvv http://localhost:8083/hello; do sleep 2; done'

      - name: debug install
        if: failure()
        run: |
          kubectl get pods -A
          kubectl get certificate -n spinkube
          kubectl logs -n spinkube -l app.kubernetes.io/name=spin-operator || true
          kubectl describe -n spinkube pod -l app.kubernetes.io/name=spin-operator || true
          kubectl logs -n spinkube -l app.kubernetes.io/name=kwasm-operator || true
          kubectl describe -n spinkube pod -l app.kubernetes.io/name=kwasm-operator || true
          kubectl logs -l core.spinoperator.dev/app-name=simple-spinapp || true
          kubectl describe pod -l core.spinoperator.dev/app-name=simple-spinapp || true

      - name: Verify curl
        run: curl localhost:8083/hello

      - name: Delete Spin App
        run: kubectl delete spinapp simple-spinapp

      # TODO: Add test (separate workflow?) around helm delete when SpinApp(Executor) resources exist
      # (helm release deletion should be blocked)

      - name: helm delete spinkube
        run: helm delete spinkube --namespace spinkube

      - name: Verify all resources are deleted
        shell: bash
        run: |
          if [[ $(kubectl get crd -o name | grep -q cert-manager) -eq 0 ]]; then
            echo "Cert-manager CRD(s) exist; failing test"
            exit 1
          fi

          if [[ $(kubectl get crd -o name | grep -q spinapp) -eq 0 ]]; then
            echo "SpinApp(Executor) CRD(s) exist; failing test"
            exit 1
          fi

          if [[ $(kubectl get ns -o name | grep -q spinkube) -eq 0 ]]; then
            echo "Namespace 'spinkube' exists; failing test"
            exit 1
          fi

      - name: debug uninstall
        if: failure()
        run: |
          kubectl get pods -A
          kubectl get crd -A
          kubectl get ns -A
