name: Marketplace Publish

on:
  push:
    tags: ["v*"]

permissions:
  contents: read

jobs:
  publish:
    name: Publish the marketplace bundle
    runs-on: ubuntu-22.04
    container: mcr.microsoft.com/container-package-app:latest
    steps:
      - uses: actions/checkout@v3

      - name: publish the bundle
        run: |
          az acr login -n ${{ secrets.AZURE_ACR }} -u ${{ secrets.AZURE_ACR }} -p ${{ secrets.AZURE_ACR_PASSWORD }}
          cd marketplace
          # Override the registry server to support publishing to alternate ACRs
          yq -i '.registryServer = "${{ secrets.AZURE_ACR }}.azurecr.io' manifest.yaml
          cpa buildbundle
